// Sample metric definitions and coverage. Later these come from GET /api/metrics.
// Metrics have a formula and the raw fields it reads; raw fields come from Finnhub.
export const metrics = [
  {
    id: 'eps_ttm',
    name: 'EPS, trailing twelve months',
    kind: 'metric',
    grain: 'quarter',
    coverage: 1.0,
    formula: 'netIncome, summed over the last 4 quarters, ÷ sharesOutstanding',
    reads: ['netIncome', 'sharesOutstanding'],
  },
  {
    id: 'net_margin',
    name: 'Net margin',
    kind: 'metric',
    grain: 'quarter',
    coverage: 1.0,
    formula: 'netIncome ÷ revenue, same quarter',
    reads: ['netIncome', 'revenue'],
  },
  {
    id: 'net_margin_pct',
    name: 'Net margin percentile vs own history',
    kind: 'metric',
    grain: 'quarter',
    coverage: 0.92,
    formula: "Share of the company's last 20 quarters with a lower net_margin. Needs 20 quarters of history.",
    reads: ['netIncome', 'revenue'],
  },
  {
    id: 'revenue_yoy',
    name: 'Revenue growth, year over year',
    kind: 'metric',
    grain: 'quarter',
    coverage: 1.0,
    formula: 'revenue ÷ revenue four quarters earlier − 1',
    reads: ['revenue'],
  },
  {
    id: 'fcf_margin',
    name: 'Free cash flow margin',
    kind: 'metric',
    grain: 'quarter',
    coverage: 0.92,
    formula: 'freeCashFlow ÷ revenue, same quarter',
    reads: ['freeCashFlow', 'revenue'],
  },
  {
    id: 'pe',
    name: 'Price / earnings',
    kind: 'metric',
    grain: 'daily',
    coverage: 1.0,
    formula: 'price ÷ eps_ttm',
    reads: ['price', 'netIncome', 'sharesOutstanding'],
  },
  {
    id: 'pe_pct',
    name: 'P/E percentile vs own history',
    kind: 'metric',
    grain: 'quarter',
    coverage: 0.92,
    formula: "Share of the company's last 20 quarter-end P/E values below today's pe. Needs 20 quarters of history.",
    reads: ['price', 'netIncome', 'sharesOutstanding'],
  },
  {
    id: 'gross_margin',
    name: 'Gross margin',
    kind: 'metric',
    grain: 'quarter',
    coverage: 0.83,
    formula: 'grossProfit ÷ revenue, same quarter',
    reads: ['grossProfit', 'revenue'],
  },
  {
    id: 'roe',
    name: 'Return on equity',
    kind: 'metric',
    grain: 'quarter',
    coverage: 1.0,
    formula: 'netIncome, summed over the last 4 quarters, ÷ totalEquity',
    reads: ['netIncome', 'totalEquity'],
  },
  {
    id: 'debt_to_equity',
    name: 'Debt / equity',
    kind: 'metric',
    grain: 'quarter',
    coverage: 1.0,
    formula: 'totalDebt ÷ totalEquity',
    reads: ['totalDebt', 'totalEquity'],
  },
  {
    id: 'dividend_yield',
    name: 'Dividend yield',
    kind: 'metric',
    grain: 'daily',
    coverage: 0.67,
    formula: 'dividendsPerShare, summed over the last 4 quarters, ÷ price',
    reads: ['dividendsPerShare', 'price'],
  },
  {
    id: 'market_cap',
    name: 'Market capitalization',
    kind: 'metric',
    grain: 'daily',
    coverage: 1.0,
    formula: 'price × sharesOutstanding',
    reads: ['price', 'sharesOutstanding'],
  },
  { id: 'revenue', name: 'Revenue', kind: 'flow', grain: 'annual, quarter', coverage: 1.0 },
  { id: 'netIncome', name: 'Net Income', kind: 'flow', grain: 'annual, quarter', coverage: 1.0 },
  { id: 'grossProfit', name: 'Gross Profit', kind: 'flow', grain: 'annual, quarter', coverage: 0.83 },
  { id: 'freeCashFlow', name: 'Free Cash Flow', kind: 'flow', grain: 'annual, quarter', coverage: 0.92 },
  { id: 'dividendsPerShare', name: 'Dividends Per Share', kind: 'flow', grain: 'annual, quarter', coverage: 0.67 },
  { id: 'totalEquity', name: 'Total Equity', kind: 'stock', grain: 'annual, quarter', coverage: 1.0 },
  { id: 'totalDebt', name: 'Total Debt', kind: 'stock', grain: 'annual, quarter', coverage: 1.0 },
  { id: 'sharesOutstanding', name: 'Shares Outstanding', kind: 'stock', grain: 'annual, quarter', coverage: 1.0 },
  { id: 'price', name: 'Price', kind: 'rate', grain: 'daily', coverage: 1.0 },
  { id: 'sector', name: 'Sector', kind: 'label', grain: '—', coverage: 1.0 },
];
